apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
  annotations:
    kubernetes.io/service-account.name: "jenkins"
type: kubernetes.io/service-account-token                                      
